#######################################
# Example MultiQC Configuration File
#######################################

# This file can be saved either in the MultiQC installation
# directory, or as ~/.multiqc_config.yaml

# Configuration settings are taken from the following locations, in order:
# - Hardcoded in MultiQC (multiqc/utils/config.py)
# - <installation_dir>/multiqc_config.yaml
# - ~/.multiqc_config.yaml
# - Command line options

# Note that all of the values below are set to the MultiQC defaults.
# It's recommended that you delete any that you don't need.

# Title to use for the report.
title: "Sequana_mapper pipeline report"




# Prepend sample names with their directory. Useful if analysing the
# sample samples with different parameters.
prepend_dirs: False

# Default output filenames
output_fn_name: multiqc_report.html
data_dir_name: multiqc_data

# Whether to create the parsed data directory in addition to the report
make_data_dir: True

# Cleaning options for sample names. Typically, sample names are detected
# from an input filename. If any of these strings are found, they and any
# text to their right will be discarded.
# For example - file1.fq.gz_trimmed.bam_deduplicated_fastqc.zip
# would be cleaned to 'file1'
# Two options here - fn_clean_exts will replace the defaults,
# extra_fn_clean_exts will append to the defaults
extra_fn_clean_exts:
    - .gz
    - .fastq
    - _R1_.cutadapt
    - _R2_.cutadapt
    - _R2_001
    - _R1_001
    - .err
    - type: remove
      pattern: '.sorted'
    - type: regex
      pattern: '^Sample_\d+'


# Ignore these files / directories / paths when searching for logs
fn_ignore_files:
    - .DS_Store
    #- '*.html'    # need the HTML otherwise fastqc does not work

fn_ignore_dirs:
    - .snakemake
    - .sequana
fn_ignore_paths:
    - '*/path/to/*_files/'

# Ignore files larger than this when searcing for logs (bytes)
# fastqc files can be as large as 1Mb
log_filesize_limit: 5000000

# MultiQC skips a couple of debug messages when searching files as the
# log can get very verbose otherwise. Re-enable here to help debugging.
report_readerrors: False
report_imgskips: False

# Opt-out of remotely checking that you're running the latest version
no_version_check: False

# How to plot graphs. Different templates can override these settings, but
# the default template can use interactive plots (Javascript using HighCharts)
# or flat plots (images, using MatPlotLib). With interactive plots, the report
# can prevent automatically rendering all graphs if there are lots of samples
# to prevent the browser being locked up when the report opens.
plots_force_flat: False          # Try to use only flat image graphs
plots_force_interactive: False   # Try to use only interactive javascript graphs
plots_flat_numseries: 100        # If neither of the above, use flat if > this number of datasets
num_datasets_plot_limit: 50      # If interactive, don't plot on load if > this number of datasets
max_table_rows: 500              # Swap tables for a beeswarm plot above this

# Overwrite module filename search patterns. See multiqc/utils/search_patterns.yaml
# for the defaults. Remove a default by setting it to null.
sp:
    star:
        fn: '*Log.final.out'
    trimmomatic:
        contents: 'Trimmomatic'
    sequana_kraken:
        fn: "sequana_kraken_summary.json"
    sequana_bamtools_stats:
        fn: "sequana_bamtools_stats*.txt"
    sequana_pacbio_qc:
        fn: "sequana_summary_pacbio_qc*.json"
    sequana_quality_control:
        fn: "summary.json"
    sequana_coverage:
        fn: "sequana_summary_coverage.json"
    sequana_isoseq:
        fn: "sequana_summary_isoseq.json"
    sequana_isoseq_qc:
        fn: "sequana_summary_isoseq_qc.json"
    sequana_pacbio_amplicon:
        fn: "sequana_pacbio_amplicon_*.json"


# Specify a custom logo to add to reports (uncomment to use)
custom_logo: .sequana/logo.png         # '/path/to/logo.png'
custom_logo_url: https://github.com/sequana/sequana_mapper
custom_logo_title: "Sequana pipeline page (mapper)"
subtitle: '<a href="https://github.com/sequana/sequana_mapper">Issues, stars, comments: visit the sequana_mapper page.</a>'
intro_text: ""

# Add generic information to the top of reports
report_header_info:
    - Authors:: '<a href="http://github.com/sequana/sequana">Sequana developers'
    #- Another field:: 'Loaded from <code>multiqc_config_example.yaml</code>'
    #- Something different:: 'You can put any key-value pairs here'
    - Want to know more?: 'See the <a href="http://sequana.readthedocs.io" target="_blank">Sequana documentation</a>'
    - Citations:: 'If you used Sequanix, Sequana or Sequana_coverage tool, please see <a href="http://sequana.readthedocs.io">How to cite ?</a> section. In particular, if you use this report in a publication, please cite Sequana. You may want to consider adding a note in the acknowledgement to thank bioinformaticians or bioanalysts for their feedbacks.'

# Overwrite the defaults of which table columns are visible by default
table_columns_visible:
    FastQC:
        percent_fails: False
        total_sequences: True
        percent_duplicates: True
        percent_gc: True
        avg_sequence_length: True
